depth:
  offset:
  - -0.006
  - 0.005
  - -0.035
  scale:
  - 1.0
  - 1.2
  - 1.0
kinematics:
  offset:
  - 0.005
  - 0.0
  - -0.003
  scale:
  - 1.0
  - 1.0
  - 1.0
pixel:
  offset:
  - -0.005
  - 0.01
  - -0.007
  scale:
  - 1.0
  - 1.1
  - 1.0
