/**:
  ros__parameters:
    color_range_list:
      black:
        max:
        - 86
        - 187
        - 196
        min:
        - 0
        - 30
        - 92
      blue:
        max:
        - 255
        - 255
        - 96
        min:
        - 0
        - 2
        - 0
      green:
        max:
        - 255
        - 106
        - 255
        min:
        - 0
        - 0
        - 0
      red:
        max:
        - 255
        - 255
        - 255
        min:
        - 0
        - 185
        - 86
      tennis:
        max:
        - 210
        - 159
        - 255
        min:
        - 31
        - 66
        - 178
      white:
        max:
        - 255
        - 155
        - 155
        min:
        - 111
        - 100
        - 100
      yellow:
        max:
        - 255
        - 177
        - 184
        min:
        - 195
        - 110
        - 146
